package report

import (
	"fmt"
	"strconv"
	"strings"

	"dochandler/internal/config"
	"dochandler/internal/model"

	"github.com/jung-kurt/gofpdf"
)

// CorrespondentSummary holds the totals for one correspondent
type CorrespondentSummary struct {
	Name          string
	TotalDocs     int
	MissingAmount int
	TotalAmount   float64
}

func ParseAmount(raw string) (float64, bool) {
	cleaned := strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(raw), "CHF"))
	if cleaned == "" {
		return 0, false
	}
	val, err := strconv.ParseFloat(cleaned, 64)
	if err != nil {
		return 0, false
	}
	return val, true
}

// NewPDF creates and initialises a new PDF with fonts and footer
func NewPDF(footerText string) (*gofpdf.Fpdf, error) {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(12, 12, 12)
	pdf.SetAutoPageBreak(true, 18)

	pdf.AddUTF8Font("DejaVu", "", config.FontRegular)
	pdf.AddUTF8Font("DejaVu", "B", config.FontBold)
	pdf.AddUTF8Font("DejaVu", "U", config.FontRegular)
	if pdf.Err() {
		return nil, fmt.Errorf("font laden fehlgeschlagen: %s", pdf.Error())
	}

	pdf.SetFooterFunc(func() {
		pdf.SetY(-10)
		pdf.SetFont("DejaVu", "", 7)
		pdf.SetTextColor(150, 150, 150)
		pdf.CellFormat(0, 5, fmt.Sprintf("Page %d  |  Paperless overview  %s  |  Generated by docHandler", pdf.PageNo(), footerText), "", 0, "C", false, 0, "")
	})

	return pdf, nil
}

// WriteCorrespondentContent writes one correspondent's content into an existing PDF
func WriteCorrespondentContent(pdf *gofpdf.Fpdf, req config.WebhookRequest, correspondentName string, years []string, yearMap map[string][]model.DocEntry, totalAll float64, totalDocs int, missingAll int) {
	// ── Title ────────────────────────────────────────────────────────────────
	pdf.SetFont("DejaVu", "B", 20)
	pdf.SetTextColor(30, 30, 30)
	pdf.CellFormat(0, 12, "Paperless overview "+correspondentName, "", 1, "L", false, 0, "")

	// ── Subtitle ─────────────────────────────────────────────────────────────
	pdf.SetFont("DejaVu", "", 9)
	pdf.SetTextColor(120, 120, 120)
	filterText := "All documents"
	if req.InvoiceOnly {
		filterText = "Invoices only"
	}
	pdf.CellFormat(0, 6, fmt.Sprintf("%s  |  %d documents  |  %d missing amount", filterText, totalDocs, missingAll), "", 1, "L", false, 0, "")
	pdf.Ln(4)

	// ── Column widths ────────────────────────────────────────────────────────
	colID := 12.0
	colDate := 22.0
	colInvoice := 28.0
	colType := 24.0
	colAmount := 26.0
	colTitle := 186.0 - colID - colDate - colInvoice - colType - colAmount

	// ── Table header ─────────────────────────────────────────────────────────
	drawTableHeader := func() {
		pdf.SetFont("DejaVu", "B", 7)
		pdf.SetFillColor(100, 140, 210)
		pdf.SetTextColor(255, 255, 255)
		pdf.CellFormat(colID, 7, "ID", "0", 0, "C", true, 0, "")
		pdf.CellFormat(colDate, 7, "Date", "0", 0, "C", true, 0, "")
		pdf.CellFormat(colInvoice, 7, "Invoice No.", "0", 0, "C", true, 0, "")
		pdf.CellFormat(colType, 7, "Type", "0", 0, "C", true, 0, "")
		pdf.CellFormat(colAmount, 7, "Amount", "0", 0, "R", true, 0, "")
		pdf.CellFormat(colTitle, 7, "Title", "0", 1, "L", true, 0, "")
		pdf.SetTextColor(30, 30, 30)
	}

	// ── Per year ─────────────────────────────────────────────────────────────
	for _, year := range years {
		entries := yearMap[year]

		pdf.SetFont("DejaVu", "B", 10)
		pdf.SetFillColor(220, 228, 245)
		pdf.SetTextColor(30, 60, 130)
		pdf.CellFormat(0, 7, "  "+year, "0", 1, "L", true, 0, "")
		pdf.Ln(1)

		drawTableHeader()

		yearTotal := 0.0
		yearMissing := 0

		for i, e := range entries {
			if i%2 == 0 {
				pdf.SetFillColor(245, 247, 252)
			} else {
				pdf.SetFillColor(255, 255, 255)
			}

			invoiceDisplay := e.InvoiceNumber
			if invoiceDisplay == "" {
				invoiceDisplay = "-"
			}

			amountDisplay := "-"
			if e.Amount != "" {
				val, ok := ParseAmount(e.Amount)
				if ok {
					yearTotal += val
					amountDisplay = fmt.Sprintf("CHF %.2f", val)
				} else {
					amountDisplay = e.Amount
				}
			} else {
				pdf.SetFillColor(255, 235, 235)
				yearMissing++
			}

			pdf.SetFont("DejaVu", "", 7)
			pdf.SetTextColor(60, 60, 60)

			// ── ID cell with clickable link ───────────────────────────────────
			docURL := fmt.Sprintf("%s/documents/%d/details", config.DocURL(), e.Doc.ID)
			x := pdf.GetX()
			y := pdf.GetY()
			pdf.SetTextColor(70, 110, 180)
			pdf.SetFont("DejaVu", "U", 7)
			pdf.CellFormat(colID, 6, fmt.Sprintf("%d", e.Doc.ID), "0", 0, "C", true, 0, "")
			pdf.LinkString(x, y, colID, 6, docURL)
			pdf.SetTextColor(60, 60, 60)
			pdf.SetFont("DejaVu", "", 7)

			// ── Remaining cells ───────────────────────────────────────────────
			pdf.CellFormat(colDate, 6, e.Date, "0", 0, "C", true, 0, "")
			pdf.CellFormat(colInvoice, 6, invoiceDisplay, "0", 0, "C", true, 0, "")
			pdf.CellFormat(colType, 6, e.DocTypeName, "0", 0, "C", true, 0, "")
			pdf.CellFormat(colAmount, 6, amountDisplay, "0", 0, "R", true, 0, "")
			pdf.CellFormat(colTitle, 6, e.Doc.Title, "0", 1, "L", true, 0, "")
		}

		// ── Year total row ────────────────────────────────────────────────────
		if req.ShowTotals {
			pdf.SetFont("DejaVu", "B", 7)
			pdf.SetFillColor(100, 140, 210)
			pdf.SetTextColor(255, 255, 255)
			labelW := colID + colDate + colInvoice + colType
			pdf.CellFormat(labelW, 7, fmt.Sprintf("  Total %s", year), "0", 0, "L", true, 0, "")
			pdf.CellFormat(colAmount, 7, fmt.Sprintf("CHF %.2f", yearTotal), "0", 0, "R", true, 0, "")
			if yearMissing > 0 {
				pdf.CellFormat(colTitle, 7, fmt.Sprintf("  %d missing amount", yearMissing), "0", 1, "L", true, 0, "")
			} else {
				pdf.CellFormat(colTitle, 7, "", "0", 1, "L", true, 0, "")
			}
			pdf.SetTextColor(30, 30, 30)
		}
		pdf.Ln(4)
	}

	// ── Grand total ──────────────────────────────────────────────────────────
	if req.ShowTotals {
		pdf.SetFont("DejaVu", "B", 9)
		pdf.SetFillColor(70, 110, 180)
		pdf.SetTextColor(255, 255, 255)
		labelW := colID + colDate + colInvoice + colType
		pdf.CellFormat(labelW, 9, "  Grand Total", "0", 0, "L", true, 0, "")
		pdf.CellFormat(colAmount, 9, fmt.Sprintf("CHF %.2f", totalAll), "0", 0, "R", true, 0, "")
		pdf.CellFormat(colTitle, 9, fmt.Sprintf("  %d documents  |  %d missing amount", totalDocs, missingAll), "0", 1, "L", true, 0, "")
	}

	// ── Document count footer row ─────────────────────────────────────────────
	if req.ShowFooterRow {
		pdf.SetFont("DejaVu", "", 8)
		pdf.SetFillColor(240, 240, 240)
		pdf.SetTextColor(80, 80, 80)
		pdf.Ln(2)
		pdf.CellFormat(colID+colDate+colInvoice+colType+colAmount, 6, "  Total documents:", "0", 0, "L", true, 0, "")
		pdf.SetFont("DejaVu", "B", 8)
		pdf.CellFormat(colTitle, 6, fmt.Sprintf("  %d", totalDocs), "0", 1, "L", true, 0, "")

		pdf.SetFont("DejaVu", "", 8)
		pdf.SetTextColor(80, 80, 80)
		pdf.CellFormat(colID+colDate+colInvoice+colType+colAmount, 6, "  Missing amount:", "0", 0, "L", true, 0, "")
		pdf.SetFont("DejaVu", "B", 8)
		if missingAll > 0 {
			pdf.SetTextColor(200, 60, 60)
		}
		pdf.CellFormat(colTitle, 6, fmt.Sprintf("  %d", missingAll), "0", 1, "L", true, 0, "")
		pdf.SetTextColor(80, 80, 80)

		pdf.SetFont("DejaVu", "", 8)
		pdf.CellFormat(colID+colDate+colInvoice+colType+colAmount, 6, "  Total amount:", "0", 0, "L", true, 0, "")
		pdf.SetFont("DejaVu", "B", 8)
		pdf.SetTextColor(30, 30, 30)
		pdf.CellFormat(colTitle, 6, fmt.Sprintf("  CHF %.2f", totalAll), "0", 1, "L", true, 0, "")
	}
}

// WriteGrandSummary writes a final summary page with totals across all correspondents
func WriteGrandSummary(pdf *gofpdf.Fpdf, summaries []CorrespondentSummary) {
	pdf.AddPage()

	pdf.SetFont("DejaVu", "B", 20)
	pdf.SetTextColor(30, 30, 30)
	pdf.CellFormat(0, 12, "Gesamtübersicht aller Korrespondenten", "", 1, "L", false, 0, "")
	pdf.SetFont("DejaVu", "", 9)
	pdf.SetTextColor(120, 120, 120)
	pdf.CellFormat(0, 6, fmt.Sprintf("%d Korrespondenten", len(summaries)), "", 1, "L", false, 0, "")
	pdf.Ln(4)

	colName := 80.0
	colDocs := 30.0
	colMissing := 30.0
	colAmount := 46.0

	pdf.SetFont("DejaVu", "B", 8)
	pdf.SetFillColor(100, 140, 210)
	pdf.SetTextColor(255, 255, 255)
	pdf.CellFormat(colName, 8, "  Korrespondent", "0", 0, "L", true, 0, "")
	pdf.CellFormat(colDocs, 8, "Dokumente", "0", 0, "C", true, 0, "")
	pdf.CellFormat(colMissing, 8, "Fehlend", "0", 0, "C", true, 0, "")
	pdf.CellFormat(colAmount, 8, "Betrag", "0", 1, "R", true, 0, "")
	pdf.SetTextColor(30, 30, 30)

	grandTotalDocs := 0
	grandTotalMissing := 0
	grandTotalAmount := 0.0

	for i, s := range summaries {
		if i%2 == 0 {
			pdf.SetFillColor(245, 247, 252)
		} else {
			pdf.SetFillColor(255, 255, 255)
		}

		pdf.SetFont("DejaVu", "", 8)
		pdf.SetTextColor(60, 60, 60)
		pdf.CellFormat(colName, 7, "  "+s.Name, "0", 0, "L", true, 0, "")
		pdf.CellFormat(colDocs, 7, fmt.Sprintf("%d", s.TotalDocs), "0", 0, "C", true, 0, "")

		if s.MissingAmount > 0 {
			pdf.SetTextColor(200, 60, 60)
			pdf.SetFont("DejaVu", "B", 8)
		}
		pdf.CellFormat(colMissing, 7, fmt.Sprintf("%d", s.MissingAmount), "0", 0, "C", true, 0, "")
		pdf.SetTextColor(60, 60, 60)
		pdf.SetFont("DejaVu", "", 8)
		pdf.CellFormat(colAmount, 7, fmt.Sprintf("CHF %.2f", s.TotalAmount), "0", 1, "R", true, 0, "")

		grandTotalDocs += s.TotalDocs
		grandTotalMissing += s.MissingAmount
		grandTotalAmount += s.TotalAmount
	}

	pdf.SetFont("DejaVu", "B", 9)
	pdf.SetFillColor(70, 110, 180)
	pdf.SetTextColor(255, 255, 255)
	pdf.Ln(1)
	pdf.CellFormat(colName, 9, "  Total", "0", 0, "L", true, 0, "")
	pdf.CellFormat(colDocs, 9, fmt.Sprintf("%d", grandTotalDocs), "0", 0, "C", true, 0, "")
	pdf.CellFormat(colMissing, 9, fmt.Sprintf("%d", grandTotalMissing), "0", 0, "C", true, 0, "")
	pdf.CellFormat(colAmount, 9, fmt.Sprintf("CHF %.2f", grandTotalAmount), "0", 1, "R", true, 0, "")
}

// GeneratePDF generates a single PDF for one correspondent
func GeneratePDF(req config.WebhookRequest, correspondentName string, outputPath string, years []string, yearMap map[string][]model.DocEntry, totalAll float64, totalDocs int, missingAll int) error {
	pdf, err := NewPDF("Paperless overview " + correspondentName)
	if err != nil {
		return err
	}
	pdf.AddPage()
	WriteCorrespondentContent(pdf, req, correspondentName, years, yearMap, totalAll, totalDocs, missingAll)
	return pdf.OutputFileAndClose(outputPath)
}

// CombinedPDFWriter holds a PDF instance for writing multiple correspondents
type CombinedPDFWriter struct {
	pdf       *gofpdf.Fpdf
	req       config.WebhookRequest
	summaries []CorrespondentSummary
}

// NewCombinedPDFWriter creates a new combined PDF writer
func NewCombinedPDFWriter(req config.WebhookRequest) (*CombinedPDFWriter, error) {
	pdf, err := NewPDF("Paperless overview All Correspondents")
	if err != nil {
		return nil, err
	}
	return &CombinedPDFWriter{pdf: pdf, req: req}, nil
}

// AddCorrespondent adds a correspondent on a new page to the combined PDF
func (w *CombinedPDFWriter) AddCorrespondent(correspondentName string, years []string, yearMap map[string][]model.DocEntry, totalAll float64, totalDocs int, missingAll int) {
	w.pdf.AddPage()
	WriteCorrespondentContent(w.pdf, w.req, correspondentName, years, yearMap, totalAll, totalDocs, missingAll)
	w.summaries = append(w.summaries, CorrespondentSummary{
		Name:          correspondentName,
		TotalDocs:     totalDocs,
		MissingAmount: missingAll,
		TotalAmount:   totalAll,
	})
}

// Save writes the combined PDF to disk
func (w *CombinedPDFWriter) Save() error {
	WriteGrandSummary(w.pdf, w.summaries)
	return w.pdf.OutputFileAndClose(config.CombinedOutputPDF())
}
