package report

import (
	"fmt"
	"strconv"
	"strings"

	"dochandler/internal/config"
	"dochandler/internal/model"

	"github.com/jung-kurt/gofpdf"
)

func ParseAmount(raw string) (float64, bool) {
	cleaned := strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(raw), "CHF"))
	if cleaned == "" {
		return 0, false
	}
	val, err := strconv.ParseFloat(cleaned, 64)
	if err != nil {
		return 0, false
	}
	return val, true
}

// NewPDF creates and initialises a new PDF with fonts and footer
func NewPDF(footerText string) (*gofpdf.Fpdf, error) {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(12, 12, 12)
	pdf.SetAutoPageBreak(true, 18)

	pdf.AddUTF8Font("DejaVu", "", config.FontRegular)
	pdf.AddUTF8Font("DejaVu", "B", config.FontBold)
	pdf.AddUTF8Font("DejaVu", "U", config.FontRegular)
	if pdf.Err() {
		return nil, fmt.Errorf("font laden fehlgeschlagen: %s", pdf.Error())
	}

	pdf.SetFooterFunc(func() {
		pdf.SetY(-10)
		pdf.SetFont("DejaVu", "", 7)
		pdf.SetTextColor(150, 150, 150)
		pdf.CellFormat(0, 5, fmt.Sprintf("Page %d  |  %s  |  Generated by myAI", pdf.PageNo(), footerText), "", 0, "C", false, 0, "")
	})

	return pdf, nil
}

// WriteCorrespondentContent writes one correspondent's content into an existing PDF
func WriteCorrespondentContent(pdf *gofpdf.Fpdf, correspondentName string, years []string, yearMap map[string][]model.DocEntry, totalAll float64, totalDocs int, missingAll int) {
	// ── Title ────────────────────────────────────────────────────────────────
	pdf.SetFont("DejaVu", "B", 20)
	pdf.SetTextColor(30, 30, 30)
	pdf.CellFormat(0, 12, "Übersicht "+correspondentName, "", 1, "L", false, 0, "")

	// ── Subtitle ─────────────────────────────────────────────────────────────
	pdf.SetFont("DejaVu", "", 9)
	pdf.SetTextColor(120, 120, 120)
	filterText := "All documents"
	if config.InvoiceOnly {
		filterText = "Invoices only"
	}
	pdf.CellFormat(0, 6, fmt.Sprintf("%s  |  %d documents  |  %d missing amount", filterText, totalDocs, missingAll), "", 1, "L", false, 0, "")
	pdf.Ln(4)

	// ── Column widths ────────────────────────────────────────────────────────
	colID := 12.0
	colDate := 22.0
	colInvoice := 28.0
	colType := 24.0
	colAmount := 26.0
	colTitle := 186.0 - colID - colDate - colInvoice - colType - colAmount

	// ── Table header ─────────────────────────────────────────────────────────
	drawTableHeader := func() {
		pdf.SetFont("DejaVu", "B", 7)
		pdf.SetFillColor(100, 140, 210)
		pdf.SetTextColor(255, 255, 255)
		pdf.CellFormat(colID, 7, "ID", "0", 0, "C", true, 0, "")
		pdf.CellFormat(colDate, 7, "Date", "0", 0, "C", true, 0, "")
		pdf.CellFormat(colInvoice, 7, "Invoice No.", "0", 0, "C", true, 0, "")
		pdf.CellFormat(colType, 7, "Type", "0", 0, "C", true, 0, "")
		pdf.CellFormat(colAmount, 7, "Amount", "0", 0, "R", true, 0, "")
		pdf.CellFormat(colTitle, 7, "Title", "0", 1, "L", true, 0, "")
		pdf.SetTextColor(30, 30, 30)
	}

	// ── Per year ─────────────────────────────────────────────────────────────
	for _, year := range years {
		entries := yearMap[year]

		pdf.SetFont("DejaVu", "B", 10)
		pdf.SetFillColor(220, 228, 245)
		pdf.SetTextColor(30, 60, 130)
		pdf.CellFormat(0, 7, "  "+year, "0", 1, "L", true, 0, "")
		pdf.Ln(1)

		drawTableHeader()

		yearTotal := 0.0
		yearMissing := 0

		for i, e := range entries {
			if i%2 == 0 {
				pdf.SetFillColor(245, 247, 252)
			} else {
				pdf.SetFillColor(255, 255, 255)
			}

			invoiceDisplay := e.InvoiceNumber
			if invoiceDisplay == "" {
				invoiceDisplay = "-"
			}

			amountDisplay := "-"
			if e.Amount != "" {
				val, ok := ParseAmount(e.Amount)
				if ok {
					yearTotal += val
					amountDisplay = fmt.Sprintf("CHF %.2f", val)
				} else {
					amountDisplay = e.Amount
				}
			} else {
				pdf.SetFillColor(255, 235, 235)
				yearMissing++
			}

			pdf.SetFont("DejaVu", "", 7)
			pdf.SetTextColor(60, 60, 60)

			// ── ID cell with clickable link ───────────────────────────────────
			docURL := fmt.Sprintf("%s/documents/%d/details", config.BaseURL, e.Doc.ID)
			x := pdf.GetX()
			y := pdf.GetY()
			pdf.SetTextColor(70, 110, 180)
			pdf.SetFont("DejaVu", "U", 7)
			pdf.CellFormat(colID, 6, fmt.Sprintf("%d", e.Doc.ID), "0", 0, "C", true, 0, "")
			pdf.LinkString(x, y, colID, 6, docURL)
			pdf.SetTextColor(60, 60, 60)
			pdf.SetFont("DejaVu", "", 7)

			// ── Remaining cells ───────────────────────────────────────────────
			pdf.CellFormat(colDate, 6, e.Date, "0", 0, "C", true, 0, "")
			pdf.CellFormat(colInvoice, 6, invoiceDisplay, "0", 0, "C", true, 0, "")
			pdf.CellFormat(colType, 6, e.DocTypeName, "0", 0, "C", true, 0, "")
			pdf.CellFormat(colAmount, 6, amountDisplay, "0", 0, "R", true, 0, "")
			pdf.CellFormat(colTitle, 6, e.Doc.Title, "0", 1, "L", true, 0, "")
		}

		// ── Year total row ────────────────────────────────────────────────────
		if config.ShowTotals {
			pdf.SetFont("DejaVu", "B", 7)
			pdf.SetFillColor(100, 140, 210)
			pdf.SetTextColor(255, 255, 255)
			labelW := colID + colDate + colInvoice + colType
			pdf.CellFormat(labelW, 7, fmt.Sprintf("  Total %s", year), "0", 0, "L", true, 0, "")
			pdf.CellFormat(colAmount, 7, fmt.Sprintf("CHF %.2f", yearTotal), "0", 0, "R", true, 0, "")
			if yearMissing > 0 {
				pdf.CellFormat(colTitle, 7, fmt.Sprintf("  %d missing amount", yearMissing), "0", 1, "L", true, 0, "")
			} else {
				pdf.CellFormat(colTitle, 7, "", "0", 1, "L", true, 0, "")
			}
			pdf.SetTextColor(30, 30, 30)
		}
		pdf.Ln(4)
	}

	// ── Grand total ──────────────────────────────────────────────────────────
	if config.ShowTotals {
		pdf.SetFont("DejaVu", "B", 9)
		pdf.SetFillColor(70, 110, 180)
		pdf.SetTextColor(255, 255, 255)
		labelW := colID + colDate + colInvoice + colType
		pdf.CellFormat(labelW, 9, "  Grand Total", "0", 0, "L", true, 0, "")
		pdf.CellFormat(colAmount, 9, fmt.Sprintf("CHF %.2f", totalAll), "0", 0, "R", true, 0, "")
		pdf.CellFormat(colTitle, 9, fmt.Sprintf("  %d documents  |  %d missing amount", totalDocs, missingAll), "0", 1, "L", true, 0, "")
	}
}

// GeneratePDF generates a single PDF for one correspondent
func GeneratePDF(correspondentName string, outputPath string, years []string, yearMap map[string][]model.DocEntry, totalAll float64, totalDocs int, missingAll int) error {
	pdf, err := NewPDF("Übersicht " + correspondentName)
	if err != nil {
		return err
	}

	pdf.AddPage()
	WriteCorrespondentContent(pdf, correspondentName, years, yearMap, totalAll, totalDocs, missingAll)

	return pdf.OutputFileAndClose(outputPath)
}

// CombinedPDFWriter holds a PDF instance for writing multiple correspondents
type CombinedPDFWriter struct {
	pdf *gofpdf.Fpdf
}

// NewCombinedPDFWriter creates a new combined PDF writer
func NewCombinedPDFWriter() (*CombinedPDFWriter, error) {
	pdf, err := NewPDF("Übersicht All Correspondents")
	if err != nil {
		return nil, err
	}
	return &CombinedPDFWriter{pdf: pdf}, nil
}

// AddCorrespondent adds a correspondent on a new page to the combined PDF
func (w *CombinedPDFWriter) AddCorrespondent(correspondentName string, years []string, yearMap map[string][]model.DocEntry, totalAll float64, totalDocs int, missingAll int) {
	w.pdf.AddPage()
	WriteCorrespondentContent(w.pdf, correspondentName, years, yearMap, totalAll, totalDocs, missingAll)
}

// Save writes the combined PDF to disk
func (w *CombinedPDFWriter) Save() error {
	return w.pdf.OutputFileAndClose(config.CombinedOutputPDF())
}
